spring:
  application:
    name: grpc-client

server:
  port: 8080

grpc:
  client:
    #host: myapp.demo-cluster.svc.cluster.local  # K8s service name in your kind cluster
    host: localhost
    port: 9090