apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-client-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /grpc-client(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grpc-client-rest
                port:
                  number: 80