
apiVersion: v1
kind: Service

metadata:
  name: grpc-client-rest

spec:
  type: {{ .Values.service.rest.type }}

  selector:
    app: grpc-client

  ports:
    - name: rest
      port: {{ .Values.service.rest.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.rest.nodePort }}