replicaCount: 1

image:
  repository: grpc-client
  tag: local
  pullPolicy: Never

rest:
  port: 8080
  nodePort: 30080

grpc:
  port: 9090
  nodePort: 30090

service:
    rest:
      type: NodePort
      port: 80
    grpc:
      type: NodePort
      port: 9090

resources: {}

env:
  SPRING_PROFILES_ACTIVE: local